#!/usr/bin/env python3
"""Generate the checked Swift/Metal executable-model contract from one JSON source."""
import argparse
import json
from pathlib import Path

SIZES = {"u32": 4, "u64": 8, "f32": 4}
COUNT_FIELDS = {
    "outcomeMetrics", "priorState", "posteriorState", "observation", "somaticAction",
    "factoredReinforcement", "teacherState", "fastPlasticityTrace", "cerebellarTrace",
    "activeSensingTrace", "autonomicAction", "activeSensingAction", "internalAction", "bodySchemaTrace",
}

def load(path):
    data = json.loads(Path(path).read_text())
    assert data["schemaVersion"] == 1
    transition = data["committedTransition"]
    cursor = 0
    seen = set()
    for field in transition["fields"]:
        assert field["name"] not in seen
        seen.add(field["name"])
        assert field["type"] in SIZES and field["count"] > 0
        assert field["offset"] == cursor, (field["name"], field["offset"], cursor)
        cursor += SIZES[field["type"]] * field["count"]
    assert cursor == transition["strideBytes"]
    assert transition["fields"][-1]["name"] == "bodySchemaTrace"
    p = data["policyHead"]
    assert p["primaryObservationCount"] + p["tailObservationCount"] == p["observationCount"]
    assert p["recurrentInputCount"] == p["somaticSynergyCount"] == p["primaryObservationCount"]
    assert 0 < p["tailFoldGain"] <= 1
    return data

def swift(data):
    t, p = data["committedTransition"], data["policyHead"]
    offsets = "\n".join(f"      public static let {f['name']} = {f['offset']}" for f in t["fields"])
    counts = "\n".join(f"      public static let {f['name']} = {f['count']}" for f in t["fields"] if f["name"] in COUNT_FIELDS)
    return f'''// GENERATED by scripts/generate-executable-model-contract.py. DO NOT EDIT.\nimport Foundation\n\npublic enum BrainExecutableModelContract {{\n  public static let schemaVersion = {data['schemaVersion']}\n\n  public enum CommittedTransition {{\n    public static let recordVersion: UInt32 = {t['recordVersion']}\n    public static let strideBytes = {t['strideBytes']}\n    public static let validFlag: UInt32 = {t['flags']['valid']}\n    public static let hasEmbodiedTraceFlag: UInt32 = {t['flags']['hasEmbodiedTrace']}\n    public static let acceptedStopFlag: UInt32 = {t['flags']['acceptedStop']}\n\n    public enum Offset {{\n{offsets}\n    }}\n\n    public enum Count {{\n{counts}\n    }}\n  }}\n\n  public enum PolicyHead {{\n    public static let recurrentInputCount = {p['recurrentInputCount']}\n    public static let observationCount = {p['observationCount']}\n    public static let primaryObservationCount = {p['primaryObservationCount']}\n    public static let tailObservationCount = {p['tailObservationCount']}\n    public static let somaticSynergyCount = {p['somaticSynergyCount']}\n    public static let tailFoldGain: Float = {p['tailFoldGain']}\n    public static let beliefEvidenceIndex = {p['beliefEvidenceIndex']}\n    public static let beliefBiasIndex = {p['beliefBiasIndex']}\n    public static let beliefRecurrentIndex = {p['beliefRecurrentIndex']}\n    public static let policyGainIndex = {p['policyGainIndex']}\n    public static let policyBiasIndex = {p['policyBiasIndex']}\n  }}\n}}\n'''

def metal(data):
    t, p = data["committedTransition"], data["policyHead"]
    return f'''// GENERATED by scripts/generate-executable-model-contract.py. DO NOT EDIT.\n#ifndef NUMIBRAIN_EXECUTABLE_MODEL_CONTRACT_METALH\n#define NUMIBRAIN_EXECUTABLE_MODEL_CONTRACT_METALH\n#define NB_CONTRACT_SCHEMA_VERSION {data['schemaVersion']}u\n#define NB_CONTRACT_COMMITTED_TRANSITION_RECORD_VERSION {t['recordVersion']}u\n#define NB_CONTRACT_COMMITTED_TRANSITION_STRIDE_BYTES {t['strideBytes']}u\n#define NB_CONTRACT_COMMITTED_TRANSITION_VALID {t['flags']['valid']}u\n#define NB_CONTRACT_COMMITTED_TRANSITION_HAS_EMBODIED_TRACE {t['flags']['hasEmbodiedTrace']}u\n#define NB_CONTRACT_COMMITTED_TRANSITION_ACCEPTED_STOP {t['flags']['acceptedStop']}u\n#define NB_CONTRACT_RECURRENT_INPUT_COUNT {p['recurrentInputCount']}u\n#define NB_CONTRACT_OBSERVATION_COUNT {p['observationCount']}u\n#define NB_CONTRACT_PRIMARY_OBSERVATION_COUNT {p['primaryObservationCount']}u\n#define NB_CONTRACT_TAIL_OBSERVATION_COUNT {p['tailObservationCount']}u\n#define NB_CONTRACT_SOMATIC_SYNERGY_COUNT {p['somaticSynergyCount']}u\n#define NB_CONTRACT_TAIL_FOLD_GAIN {p['tailFoldGain']}f\n#define NB_CONTRACT_BELIEF_EVIDENCE_INDEX {p['beliefEvidenceIndex']}u\n#define NB_CONTRACT_BELIEF_BIAS_INDEX {p['beliefBiasIndex']}u\n#define NB_CONTRACT_BELIEF_RECURRENT_INDEX {p['beliefRecurrentIndex']}u\n#define NB_CONTRACT_POLICY_GAIN_INDEX {p['policyGainIndex']}u\n#define NB_CONTRACT_POLICY_BIAS_INDEX {p['policyBiasIndex']}u\n#endif\n'''

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--contract", default="Contracts/NumiBrainExecutableModelV1.json")
    parser.add_argument("--swift", default="Sources/NumiBrainCore/Generated/BrainExecutableModelContract.generated.swift")
    parser.add_argument("--metal", default="Sources/NumiBrainMetal/Shaders/GeneratedExecutableModelContract.metalh")
    args = parser.parse_args()
    data = load(args.contract)
    Path(args.swift).parent.mkdir(parents=True, exist_ok=True)
    Path(args.metal).parent.mkdir(parents=True, exist_ok=True)
    Path(args.swift).write_text(swift(data))
    Path(args.metal).write_text(metal(data))

if __name__ == "__main__":
    main()
